# Generated by Django 2.0.4 on 2018-04-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagcount',
            options={'ordering': ['-count']},
        ),
    ]
