# Generated by Django 2.0.4 on 2018-04-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0002_auto_20180426_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagcount',
            options={'ordering': ['-count', '-tag_id']},
        ),
    ]
