# Generated by Django 2.0.4 on 2018-04-17 19:42

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_auto_20180410_0608'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=3000)),
                ('answer', models.CharField(max_length=3000, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_from_student', to='authentication.StudentModel')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('to_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_to_student', to='authentication.StudentModel')),
            ],
        ),
    ]
