# Generated by Django 2.0.4 on 2018-04-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ask',
            old_name='student',
            new_name='from_student',
        ),
    ]
