# Generated by Django 2.0.4 on 2018-04-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20180417_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ask',
            name='answer',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
