# Generated by Django 2.0.4 on 2018-04-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_auto_20180418_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ask',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
