# Generated by Django 2.0.4 on 2018-04-16 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20180410_0608'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.StudentModel'),
            preserve_default=False,
        ),
    ]
