# Generated by Django 2.0.4 on 2018-04-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20180410_0608'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0004_likes_is_liked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('content_type', 'object_id', 'student')},
        ),
    ]
