# Generated by Django 2.0.4 on 2018-04-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0005_auto_20180416_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='is_liked',
        ),
    ]
