# Generated by Django 2.0.4 on 2018-04-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0006_remove_likes_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='modified_at',
        ),
    ]
