# Generated by Django 2.0.4 on 2018-04-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180409_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='year',
            field=models.DecimalField(choices=[(1, '1st year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], decimal_places=0, max_digits=1),
        ),
    ]
