# Generated by Django 2.0.4 on 2018-04-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20180410_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
