# Generated by Django 2.0.4 on 2018-04-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_studentmodel_profile_picture_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='profile_picture_url',
            new_name='profile_picture_large_url',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='profile_picture_small_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
