# Generated by Django 2.0.4 on 2018-04-22 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20180422_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
