# Generated by Django 2.0.4 on 2018-04-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20180422_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='passout_year',
            field=models.DecimalField(blank=True, choices=[(2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], decimal_places=0, default=2019, max_digits=4, null=True),
        ),
    ]
