# Generated by Django 2.0.4 on 2018-04-11 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_auto_20180410_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('confession_clip_url', models.URLField(max_length=256)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.StudentModel')),
            ],
        ),
    ]
