# Generated by Django 2.0.4 on 2018-04-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confessions',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
