# Generated by Django 2.0.4 on 2018-04-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0002_confessions_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='confessions',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
