# Generated by Django 2.0.4 on 2018-04-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0003_confessions_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='confessions',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
