# Generated by Django 2.0.4 on 2018-04-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0004_confessions_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='confessions',
            name='confession_clip_duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confessions',
            name='confession_clip_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
