# Generated by Django 2.0.4 on 2018-04-17 08:06

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('confessions', '0005_auto_20180415_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='confessions',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
