# Generated by Django 2.0.4 on 2018-05-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0007_auto_20180426_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confessions',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
